apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: order-processor-config
spec:
  tracing:
    samplingRate: '1'
    zipkin:
      endpointAddress: 'http://localhost:9411/api/v2/spans'
  metric:
    enabled: true
  accessControl:
    defaultAction: allow
    trustDomain: 'public'
